#!/bin/sh

REPO=$HOME/github/home/.git

[ $# -eq 0 ] &&
    echo "CIT is alias for Config gIT with predefined --git-dir=$REPO and --work-tree=$HOME" &&
    echo &&
    echo 'for use:' &&
    echo "$ git clone git@github.com:aiquie/home.git $(dirname $REPO)" &&
    echo "$ cit config status.showUntrackedFiles no" &&
    exit 1

[ ! -d $REPO ] && echo "error: not found config repository $REPO" && exit 2

git --git-dir=$REPO --work-tree=$HOME "$@"
