#!/bin/sh

HTML_URL="$@"

[ -n "${MIRROR_PATH}" ] && MIRROR_PATH="."

wget                                    \
    --no-verbose                        \
    --recursive                         \
    --no-parent                         \
    --relative                          \
    --convert-links                     \
    --page-requisites                   \
    --directory-prefix="${MIRROR_PATH}" \
    --reject "robots.txt"               \
    ${HTML_URL}

